### PR TITLE
Updates to PyQt5

### PR DESCRIPTION
**Pull request by rockbot**
Hi! PyQt4 is no longer being maintained, so I took the liberty of upgrading this project from PyQt4 to PyQt5. It seems to work as intended - I hope it's helpful!

### CODE REVIEW

**Comment by JeanPaul20** [comment]
Nice one, thank you

**Comment by JeanPaul20** [comment]
What version of Python to you use to compile the program, 3.5 or the latest 3.8.1 ?

**Comment by grig8693** [comment]
Hello every one)) It Will be very helpful if update Pyqt4 to pyqt5 and puthon 3.7 and higher))

**Comment by 1900zyh** [comment]
Hi @rockbot thank you so much for your contribution!
I have merged this pull request, everything goes well. 
I used pyqt5 and python3.5 for testing on macOS.

**Pull request merged**
